<?php

function CT_CTDI_import_files() {

    $premium_buy_url = 'http://www.crafthemes.com/apex-business-pro';

    return array(
        array(
            'import_file_name'           => __( 'Main', 'ct-ctdi' ),
            'categories'                 => array( 'Business' ),
            'import_file_url'            => 'https://dc.crafthemes.com/apex-main/apex-main-export.xml',
            'import_widget_file_url'     => 'https://dc.crafthemes.com/apex-main/apex-main-widgets.wie',
            'import_customizer_file_url' => 'https://dc.crafthemes.com/apex-main/apex-main-customizer.dat',
            'import_preview_image_url'   => 'https://dc.crafthemes.com/apex-main/screenshot.png',
            'preview_url'                => 'http://www.crafthemes.com/go/demo-apex',
        ),
        array(
            'import_file_name'           => __( 'Startup', 'ct-ctdi' ),
            'categories'                 => array( 'Business' ),
            'import_file_url'            => 'https://dc.crafthemes.com/apex-startup/apex-export.xml',
            'import_widget_file_url'     => 'https://dc.crafthemes.com/apex-startup/apex-widgets.wie',
            'import_customizer_file_url' => 'https://dc.crafthemes.com/apex-startup/apex-customizer.dat',
            'import_preview_image_url'   => 'https://dc.crafthemes.com/apex-startup/screenshot.jpg',
            'preview_url'                => 'http://www.crafthemes.com/go/demo-apex-startup',
            'premium_url'                => $premium_buy_url,
        ),
        array(
            'import_file_name'           => __( 'Business', 'ct-ctdi' ),
            'categories'                 => array( 'Business' ),
            'import_file_url'            => 'https://dc.crafthemes.com/apex-business/apex-business-export.xml',
            'import_widget_file_url'     => 'https://dc.crafthemes.com/apex-business/apex-business-widgets.wie',
            'import_customizer_file_url' => 'https://dc.crafthemes.com/apex-business/apex-business-customizer.dat',
            'import_preview_image_url'   => 'https://dc.crafthemes.com/apex-business/screenshot.jpg',
            'preview_url'                => 'http://www.crafthemes.com/go/demo-apex-business',
        ),
        array(
            'import_file_name'           => __( 'Corporate', 'ct-ctdi' ),
            'categories'                 => array( 'Business' ),
            'import_file_url'            => 'https://dc.crafthemes.com/apex-corporate/apex-export.xml',
            'import_widget_file_url'     => 'https://dc.crafthemes.com/apex-corporate/apex-widgets.wie',
            'import_customizer_file_url' => 'https://dc.crafthemes.com/apex-corporate/apex-customizer.dat',
            'import_preview_image_url'   => 'https://dc.crafthemes.com/apex-corporate/screenshot.jpg',
            'preview_url'                => 'http://www.crafthemes.com/go/demo-apex-corporate',
            'premium_url'                => $premium_buy_url,
        ),
        array(
            'import_file_name'           => __( 'Blog', 'ct-ctdi' ),
            'categories'                 => array( 'Blog' ),
            'import_file_url'            => 'https://dc.crafthemes.com/apex-blog/apex-export.xml',
            'import_widget_file_url'     => 'https://dc.crafthemes.com/apex-blog/apex-widgets.wie',
            'import_customizer_file_url' => 'https://dc.crafthemes.com/apex-blog/apex-customizer.dat',
            'import_preview_image_url'   => 'https://dc.crafthemes.com/apex-blog/screenshot.jpg',
            'preview_url'                => 'http://www.crafthemes.com/go/demo-apex-blog',
            'premium_url'                => '',
        ),
        array(
            'import_file_name'           => __( 'Solution', 'ct-ctdi' ),
            'categories'                 => array( 'Business' ),
            'import_file_url'            => 'https://dc.crafthemes.com/apex-solution/apex-export.xml',
            'import_customizer_file_url' => 'https://dc.crafthemes.com/apex-solution/apex-customizer.dat',
            'import_preview_image_url'   => 'https://dc.crafthemes.com/apex-solution/screenshot.jpg',
            'preview_url'                => 'http://www.crafthemes.com/go/demo-apex-solution',
            'premium_url'                => $premium_buy_url,
        ),
        array(
            'import_file_name'           => __( 'Trainer', 'ct-ctdi' ),
            'categories'                 => array( 'Trainer' ),
            'import_file_url'            => 'https://dc.crafthemes.com/apex-trainer/apex-export.xml',
            'import_customizer_file_url' => 'https://dc.crafthemes.com/apex-trainer/apex-customizer.dat',
            'import_preview_image_url'   => 'https://dc.crafthemes.com/apex-trainer/screenshot.jpg',
            'preview_url'                => 'http://www.crafthemes.com/go/demo-apex-trainer',
            'premium_url'                => ''
        ),
        array(
            'import_file_name'           => __( 'Medical', 'ct-ctdi' ),
            'categories'                 => array( 'Medical', 'Medical' ),
            'import_file_url'            => 'https://dc.crafthemes.com/apex-medical/apex-export.xml',
            'import_widget_file_url'     => 'https://dc.crafthemes.com/apex-medical/apex-widgets.wie',
            'import_customizer_file_url' => 'https://dc.crafthemes.com/apex-medical/apex-customizer.dat',
            'import_preview_image_url'   => 'https://dc.crafthemes.com/apex-medical/screenshot.jpg',
            'preview_url'                => 'http://www.crafthemes.com/go/demo-apex-medical',
            'premium_url'                => '',
        ),
        array(
            'import_file_name'           => __( 'Landing', 'ct-ctdi' ),
            'categories'                 => array( 'Business' ),
            'import_file_url'            => 'https://dc.crafthemes.com/apex-landing/apex-export.xml',
            'import_customizer_file_url' => 'https://dc.crafthemes.com/apex-landing/apex-customizer.dat',
            'import_preview_image_url'   => 'https://dc.crafthemes.com/apex-landing/screenshot.jpg',
            'preview_url'                => 'http://www.crafthemes.com/go/demo-apex-landing',
            'premium_url'                => $premium_buy_url,
        ),
        array(
            'import_file_name'           => __( 'Gym', 'ct-ctdi' ),
            'categories'                 => array( 'Trainer' ),
            'import_file_url'            => 'https://dc.crafthemes.com/apex-gym/apex-export.xml',
            'import_customizer_file_url' => 'https://dc.crafthemes.com/apex-gym/apex-customizer.dat',
            'import_preview_image_url'   => 'https://dc.crafthemes.com/apex-gym/screenshot.jpg',
            'preview_url'                => 'http://www.crafthemes.com/go/demo-apex-gym',
            'premium_url'                => '',
        ),
        array(
            'import_file_name'           => __( 'Cleaning', 'ct-ctdi' ),
            'categories'                 => array( 'Cleaning' ),
            'import_file_url'            => 'https://dc.crafthemes.com/apex-cleaning/apex-export.xml',
            'import_customizer_file_url' => 'https://dc.crafthemes.com/apex-cleaning/apex-customizer.dat',
            'import_preview_image_url'   => 'https://dc.crafthemes.com/apex-cleaning/screenshot.jpg',
            'preview_url'                => 'http://cleaning.crafthemes-demo.com/',
            'premium_url'                => $premium_buy_url,
        ),
        array(
            'import_file_name'           => __( 'Construction', 'ct-ctdi' ),
            'categories'                 => array( 'Business' ),
            'import_file_url'            => 'https://dc.crafthemes.com/apex-construction/apex-export.xml',
            'import_customizer_file_url' => 'https://dc.crafthemes.com/apex-construction/apex-customizer.dat',
            'import_preview_image_url'   => 'https://dc.crafthemes.com/apex-construction/screenshot.jpg',
            'preview_url'                => 'http://www.crafthemes.com/go/demo-apex-construction',
            'premium_url'                => $premium_buy_url,
        ),
        array(
            'import_file_name'           => __( 'Portfolio', 'ct-ctdi' ),
            'categories'                 => array( 'Portfolio' ),
            'import_file_url'            => '',
            'import_preview_image_url'   => 'https://dc.crafthemes.com/apex-portfolio/screenshot.jpg',
            'preview_url'                => 'http://www.crafthemes.com/go/demo-apex-portfolio',
            'import_file_url'            => 'https://dc.crafthemes.com/apex-portfolio/apex-export.xml',
            'import_customizer_file_url' => 'https://dc.crafthemes.com/apex-portfolio/apex-customizer.dat',
        ),
        array(
            'import_file_name'           => __( 'Restaurant', 'ct-ctdi' ),
            'categories'                 => array( 'Business', 'Food' ),
            'import_file_url'            => 'https://dc.crafthemes.com/apex-restaurant/apex-export.xml',
            'import_customizer_file_url' => 'https://dc.crafthemes.com/apex-restaurant/apex-customizer.dat',
            'import_preview_image_url'   => 'https://dc.crafthemes.com/apex-restaurant/screenshot.jpg',
            'preview_url'                => 'http://www.crafthemes.com/go/demo-apex-restaurant',
            'premium_url'                => $premium_buy_url,
        ),
        array(
            'import_file_name'           => __( 'Charity', 'ct-ctdi' ),
            'categories'                 => array( 'Charity' ),
            'import_file_url'            => 'https://dc.crafthemes.com/apex-charity/apex-export.xml',
            'import_customizer_file_url' => 'https://dc.crafthemes.com/apex-charity/apex-customizer.dat',
            'import_preview_image_url'   => 'https://dc.crafthemes.com/apex-charity/screenshot.jpg',
            'preview_url'                => 'http://www.crafthemes.com/go/demo-apex-charity',
            'premium_url'                => ''
        ),
        array(
            'import_file_name'           => __( 'Dental', 'ct-ctdi' ),
            'categories'                 => array( 'Medical' ),
            'import_file_url'            => 'https://dc.crafthemes.com/apex-dental/apex-export.xml',
            'import_customizer_file_url' => 'https://dc.crafthemes.com/apex-dental/apex-customizer.dat',
            'import_preview_image_url'   => 'https://dc.crafthemes.com/apex-dental/screenshot.jpg',
            'preview_url'                => 'https://dental.crafthemes-demo.com',
            'additional_plugin'          => 'smart-slider-3',
            'premium_url'                => $premium_buy_url,
        ),
        array(
            'import_file_name'           => __( 'Logistics', 'ct-ctdi' ),
            'categories'                 => array( 'Business' ),
            'import_file_url'            => 'https://dc.crafthemes.com/apex-logistics/apex-export.xml',
            'import_customizer_file_url' => 'https://dc.crafthemes.com/apex-logistics/apex-customizer.dat',
            'import_widget_file_url'     => 'https://dc.crafthemes.com/apex-logistics/apex-widgets.wie',
            'import_preview_image_url'   => 'https://dc.crafthemes.com/apex-logistics/screenshot.jpg',
            'preview_url'                => 'http://www.crafthemes.com/go/demo-apex-logistics',
            'premium_url'                => $premium_buy_url,
        ),
        array(
            'import_file_name'           => __( 'Agency', 'ct-ctdi' ),
            'categories'                 => array( 'Business' ),
            'import_file_url'            => 'https://dc.crafthemes.com/apex-agency/apex-export.xml',
            'import_customizer_file_url' => 'https://dc.crafthemes.com/apex-agency/apex-customizer.dat',
            'import_preview_image_url'   => 'https://dc.crafthemes.com/apex-agency/screenshot.jpg',
            'preview_url'                => 'http://www.crafthemes.com/go/demo-apex-agency',
            'premium_url'                => $premium_buy_url,
        ),
        array(
            'import_file_name'           => __( 'Basic', 'ct-ctdi' ),
            'categories'                 => array( 'Business' ),
            'import_file_url'            => 'https://dc.crafthemes.com/apex-basic/apex-export.xml',
            'import_customizer_file_url' => 'https://dc.crafthemes.com/apex-basic/apex-customizer.dat',
            'import_preview_image_url'   => 'https://dc.crafthemes.com/apex-basic/screenshot.jpg',
            'preview_url'                => 'http://www.crafthemes.com/go/demo-apex-basic',
        ),
        array(
            'import_file_name'           => __( 'Spa', 'ct-ctdi' ),
            'categories'                 => array( 'Business' ),
            'import_file_url'            => 'https://dc.crafthemes.com/apex-spa/apex-export.xml',
            'import_customizer_file_url' => 'https://dc.crafthemes.com/apex-spa/apex-customizer.dat',
            'import_preview_image_url'   => 'https://dc.crafthemes.com/apex-spa/screenshot.jpg',
            'preview_url'                => 'http://www.crafthemes.com/go/demo-apex-spa',
            'premium_url'                => $premium_buy_url,
        ),
        array(
            'import_file_name'           => __( 'Interior', 'ct-ctdi' ),
            'categories'                 => array( 'Business' ),
            'import_file_url'            => 'https://dc.crafthemes.com/apex-interior/apex-export.xml',
            'import_customizer_file_url' => 'https://dc.crafthemes.com/apex-interior/apex-customizer.dat',
            'import_preview_image_url'   => 'https://dc.crafthemes.com/apex-interior/screenshot.jpg',
            'preview_url'                => 'http://interior.crafthemes-demo.com/',
        ),
        array(
            'import_file_name'           => __( 'Education', 'ct-ctdi' ),
            'categories'                 => array( 'Education' ),
            'import_file_url'            => 'https://dc.crafthemes.com/apex-edu/apex-export.xml',
            'import_customizer_file_url' => 'https://dc.crafthemes.com/apex-edu/apex-customizer.dat',
            'import_preview_image_url'   => 'https://dc.crafthemes.com/apex-edu/screenshot.jpg',
            'preview_url'                => 'https://edu.crafthemes-demo.com/',
        ),
        array(
            'import_file_name'           => __( 'Gaming', 'ct-ctdi' ),
            'categories'                 => array( 'Business' ),
            'import_file_url'            => 'https://dc.crafthemes.com/apex-gaming/apex-export.xml',
            'import_customizer_file_url' => 'https://dc.crafthemes.com/apex-gaming/apex-customizer.dat',
            'import_preview_image_url'   => 'https://dc.crafthemes.com/apex-gaming/screenshot.jpg',
            'preview_url'                => 'https://gaming.crafthemes-demo.com',
            'premium_url'                => $premium_buy_url,
        ),
    );
}
